# Site settings
title: Muse Bridal
email: contact@musebridal.co.uk
description: > # Bridal outfitter in Newport, Shropshire.
baseurl: ""
url: "http://www.musebridal.co.uk/"
# url: "/Users/jack/dev/musebridal/_site/"

# Build settings
markdown: kramdown
ignore: [node_modules, package.json]
