# Site settings
title: Muse Bridal
email: contact@musebridal.co.uk
description: > # Bridal outfitter in Newport, Shropshire.
baseurl: ""
url: "http://musebridal.co.uk/"

# Build settings
markdown: kramdown
ignore: [node_modules, package.json]
