# Site settings
title: Muse Birdal
email: contact@musebridal.co.uk
description: > # Bridal outfitter in Newport, Shropshire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://musebridal.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
ignore: [node_modules]